### ISSUE TITLE
GUI configurator

### ISSUE THREAD

**Issue by darksworm** [darksworm/emojigun#9]
Need a tool which translates all the CLI options to a more noob friendly GUI.

**Comment by darksworm** [comment]
options listed in descending priority:

- [ ] start on system launch (not sure if can be done on linux, could be windows only)
- [x] bind/unbind hotkey
- [x] image directory
- [x] output image size (resize image?)
- [ ] initial mode

- [ ] grid size
- [ ] window size
- [ ] image padding
- [ ] image margin

**Comment by darksworm** [comment]
working on this together with #16

**Comment by darksworm** [comment]
Must have the output image size for this milestone

**Comment by darksworm** [comment]
Closing as the main ones have been implemented. The other ones will be addressed separate issue.
